export const title = 'Platform'
export const menus =[
    {
        label:'Tasks',
        path:'/platform/tasks',
        query:{},
        icon:'',
        children:[
            {
                label:'All',
                path:'?status=all',
                query:{},
                icon:'',
            },
            {
                label:'New',
                path:'/new',
                query:{},
                icon:'',
            },
            {
                label:'Processing',
                path:'/processing',
                query:{},
                icon:'',
            },
            {
                label:'Today',
                path:'/today',
                query:{},
                icon:'',
            },
            {
                label:'Future',
                path:'/future',
                query:{},
                icon:'',
            },
            {
                label:'Unassigned',
                path:'/unassigned',
                query:{},
                icon:'',
            },
        ]
    },
    {
        label:'Tasks',
        path:'/platform/tasks-new',
        query:{},
        icon:'',
        children:[
            {
                label:'All',
                path:'?status=all',
                query:{},
                icon:'',
            },
            {
                label:'New',
                path:'/new',
                query:{},
                icon:'',
            },
            {
                label:'Processing',
                path:'/processing',
                query:{},
                icon:'',
            },
            {
                label:'Today',
                path:'/today',
                query:{},
                icon:'',
            },
            {
                label:'Future',
                path:'/future',
                query:{},
                icon:'',
            },
            {
                label:'Unassigned',
                path:'/unassigned',
                query:{},
                icon:'',
            },
        ]
    },
    {
        label:'Leads',
        path:'/platform/leads',
        query:{},
        icon:'',
        children:[
            {
                label:'All',
                path:'',
                query:{},
                icon:'',
            },
            {
                label:'New',
                path:'',
                query:{status:'new'},
                icon:'',
            },
            {
                label:'Processing',
                path:'',
                query:{status:'processing'},
                icon:'',
            },
            {
                label:'Today',
                path:'',
                query:{status:'today'},
                icon:'',
            },
            {
                label:'Future',
                path:'',
                query:{status:'future'},
                icon:'',
            },
            {
                label:'Unassigned',
                path:'',
                query:{status:'unassigned'},
                icon:'',
            },
        ]
    }
]

