import { library } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import * as fa from '@fortawesome/free-solid-svg-icons';
import * as far from '@fortawesome/free-regular-svg-icons';
import * as fab from '@fortawesome/free-brands-svg-icons';


const iconsToUse = [
    fa.faCircleRadiation,
    fa.faPhone,
    fa.faSun,
    fa.faScrewdriverWrench,
    fa.faTrash,
    fa.faHeart,
    fa.faArrowRight,
    fa.faChevronRight,
    fa.faChevronUp,
    fa.faStar,
    fa.faPlus,
    fa.faXmark,
    fa.faSpinner,
    fa.faCircleNotch,
    fa.faBars,
    fa.faStopwatch,
    fa.faCaretDown,
    fa.faSignal,
    fa.faSignature,
    fa.faThumbsUp,
    fa.faPen,
    fa.faCopy,
    fa.faCheck,
    fa.faCircleCheck,
    fa.faPuzzlePiece,
    fa.faCircleUser,
    fa.faEllipsisVertical,
    fa.faUpRightFromSquare,
    fa.faShareNodes,
    fa.faClipboardList,
    fa.faCircleQuestion,
    fa.faLock,
    fa.faGem,
    fa.faCalendar,
    fa.faBoxArchive,
    fa.faMagnifyingGlass,
    fa.faClockRotateLeft,
    fa.faDownload,
    fa.faPaperPlane,
    fa.faFileLines,
    fa.faUser,
    fa.faCheckCircle,
    fa.faGripVertical,
    fa.faBatteryThreeQuarters,
    fa.faSolarPanel,
    fa.faArrowRightArrowLeft,
    fa.faTablet,
    fa.faGear,
    fa.faArrowRotateRight,
    fa.faDroplet,
    fa.faUserPlus,
    fa.faTag,
    fa.faCaretDown,
    fa.faCircleXmark,
    fa.faEye,
    fa.faEyeSlash,
    fa.faDollarSign,
    fa.faCircleMinus,
    fa.faCircleInfo,
    // Regular
    far.faSquare,
    far.faSquareMinus,
    far.faSquareCheck,
    far.faPenToSquare,
    far.faThumbsUp,
    far.faCalendarCheck,
    far.faClock,
    fab.faInstagram,
    fab.faFacebook
];

library.add(iconsToUse)

export { FontAwesomeIcon };
