import { library } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import * as fa from '@fortawesome/free-solid-svg-icons';
import * as far from '@fortawesome/free-regular-svg-icons';


const iconsToUse = [
    fa.faTrash,
    fa.faArrowLeft,
    fa.faArrowRight,
    fa.faChevronLeft,
    fa.faChevronRight,
    fa.faChevronUp,
    fa.faChevronDown,
    fa.faFileUpload,
    fa.faUpload,
    fa.faPlus,
    fa.faXmark,
    fa.faSpinner,
    fa.faCircleNotch,
    fa.faBars,
    fa.faStopwatch,
    fa.faCaretDown,
    fa.faSignal,
    fa.faSignature,
    fa.faThumbsUp,
    fa.faPen,
    fa.faCopy,
    fa.faCheck,
    fa.faCircleCheck,
    fa.faPuzzlePiece,
    fa.faCircleUser,
    fa.faEllipsisVertical,
    fa.faUpRightFromSquare,
    fa.faShareNodes,
    fa.faClipboardList,
    fa.faCircleQuestion,
    fa.faLock,
    fa.faGem,
    fa.faCalendar,
    fa.faBoxArchive,
    fa.faMagnifyingGlass,
    fa.faClockRotateLeft,
    fa.faDownload,
    fa.faPaperPlane,
    fa.faFileLines,
    fa.faUser,
    fa.faCheckCircle,
    fa.faGripVertical,
    fa.faBatteryThreeQuarters,
    fa.faSolarPanel,
    fa.faArrowRightArrowLeft,
    fa.faTablet,
    fa.faGear,
    fa.faArrowRotateRight,
    fa.faDroplet,
    fa.faFolderOpen,
    fa.faMapLocationDot,
    fa.faSolarPanel,
    fa.faUsers,
    fa.faCartShopping,
    fa.faSquare,
    fa.faSquareCheck,
    fa.faSquareMinus,
    fa.faList,
    fa.faListCheck,
    fa.faPlusMinus,
    fa.faBookOpenReader,
    fa.faFilter,
    fa.faUserCheck,
    fa.faAlignRight,
    fa.faAngleRight,
    fa.faHandshake,
    fa.faHashtag,
    fa.faRotateRight,
    fa.faSitemap,
    fa.faMagnifyingGlassLocation,
    fa.faFolderOpen,
    fa.faHandHoldingUsd,
    fa.faCircleInfo,
    fa.faBell,
    fa.faCog,
    fa.faMessage,
    fa.faUser,
    fa.faChartSimple,
    fa.faBookOpen,
    fa.faLayerGroup,
    fa.faChartPie,
    fa.faAngleDown,
    fa.faCircleDot,
    fa.faListCheck,
    fa.faSliders,
    fa.faIdBadge,
    fa.faSquareCaretDown,
    fa.faEllipsisVertical,
    fa.faMailReply,
    fa.faEnvelope,
    fa.faPhone,
    fa.faCopy,
    fa.faArrowUpRightFromSquare,
    fa.faUserPlus,
    fa.faUserCheck,
    fa.faStopwatch,
    fa.faClock,
    fa.faListCheck,
    // Regular
    far.faSquare,
    far.faSquareMinus,
    far.faSquareCheck,
    far.faPenToSquare,
    far.faThumbsUp,
    far.faCalendarCheck,
    far.faClock,
];

library.add(iconsToUse)

export { FontAwesomeIcon };