<script>
import Pricing from './components/Pricing.vue';

export default {
  name:'ProfileIndex',
    data() {
      return{
      }
    },
    components:{
        Pricing
    }
  }
  
</script>

<template>

  <div class="content content-y-100vh">
    
    <div class="content-header">
        <h1 class="mb-3">Solar design</h1>
        <p class="w-lg-75 sub-title pe-5">
            The settings below are used as default values for your Observer solar designs. All new designs will be created with these values.
            <br><br>
            Changes to these settings <strong>will not affect</strong> your existing designs.
        </p>
    </div>

    <div class="content-body">
        <section class="">
            
            <div class="row">
                <div class="col-lg-2 col-12 mb-3 mb-lg-0">
                    <div class="settings-group-header">
                        <h2>Solar system</h2>
                        <span class="sub-title">The default layout and configuration of the solar system.</span>
                    </div>
                </div>
                <div class="col-lg-5 col-12">

                    <div class="settings-group-item">
                        <label class="form-label-title" for="">Panel tilt angle</label>
                        <input type="text" class="form-control">
                        <span class="form-input-commant">All new panels placed in the editor will be tilted to this angle. Panels can be tilted to any angle after placing them.</span>
                    </div>
                    <div class="settings-group-item">
                        <label class="form-label-title" for="">System efficiency</label>
                        <input type="text" class="form-control">
                    </div>
                    <div class="settings-group-item">
                        <label class="form-label-title" for="">Self-consumption</label>
                        <input type="text" class="form-control">
                        <span class="form-input-commant">The portion of electricity generated by the solar system that is consumed by the customer.</span>
                    </div>
                    <div class="settings-group-item">
                        <label class="form-label-title" for="">Export limit (instantaneous)</label>
                        <input type="text" class="form-control">
                    </div>
                    <div class="settings-group-item">
                        <label class="form-label-title" for="">Installation days</label>
                        <input type="text" class="form-control">
                        <span class="form-input-commant">When you create a design, it will be marked for installation this many days in the future.</span>
                    </div>
                    <div class="">
                        <button class="btn btn-primary fw-bold">Save Settings</button>
                    </div>
                </div>
            </div>

            <hr class="mt-4 mb-5">

            <div class="row">
                <div class="col-lg-2 col-12 mb-3 mb-lg-0">
                    <div class="settings-group-header">
                        <h2>Editor</h2>
                        <span class="sub-title">These settings customise the map editor.</span>
                    </div>
                </div>
                <div class="col-lg-5 col-12">

                    <div class="settings-group-item">
                        <label class="form-label-title" for="">Azimuth basis</label>
                        <div class="select-box">
                            <select class="form-control" name="" id="">
                                <option value="">North</option>
                            </select>
                        </div>
                        <span class="form-input-commant">Azimuth will be shown as 0 when panels are pointed at this pole.</span>
                    </div>
                    <div class="">
                        <button class="btn btn-primary fw-bold">Save Settings</button>
                    </div>
                </div>
            </div>

            <hr class="mt-4 mb-5">

            <div class="row">
                <div class="col-lg-2 col-12 mb-3 mb-lg-0">
                    <div class="settings-group-header">
                        <h2>Financial settings</h2>
                        <span class="sub-title">These settings affect the solar system's financial outcomes.</span>
                    </div>
                </div>
                <div class="col-lg-5 col-12">

                    <div class="settings-group-item">
                        <label class="form-label-title" for="">Financial term (years)</label>
                        <input class="form-control" name="" id="">
                        <span class="form-input-commant">The period of time assigned as the lifespan of the purchased system or investment. This is typically between 20 to 30 years as per manufacturers warranty.</span>
                    </div>
                    <div class="">
                        <button class="btn btn-primary fw-bold">Save Settings</button>
                    </div>
                </div>
            </div>

            <hr class="mt-4 mb-5">

            <div class="row">
                <div class="col-lg-2 col-12 mb-3 mb-lg-0">
                    <div class="settings-group-header">
                        <h2>Electricity tariffs</h2>
                    </div>
                </div>
                <div class="col-lg-5 col-12">

                    <div class="settings-group-item">
                        <label class="form-label-title" for="">Quarterly bill</label>
                        <input class="form-control" name="" id="">
                    </div>

                    <div class="settings-group-item">
                        <label class="form-label-title" for="">Electricity rate (per kWh)</label>
                        <input class="form-control" name="" id="">
                    </div>

                    <div class="settings-group-item">
                        <label class="form-label-title" for="">Feed in tariff (per kWh)</label>
                        <input class="form-control" name="" id="">
                    </div>

                    <div class="settings-group-item">
                        <label class="form-label-title" for="">Daily supply charge</label>
                        <input class="form-control" name="" id="">
                    </div>
                    <div class="">
                        <button class="btn btn-primary fw-bold">Save Settings</button>
                    </div>
                </div>
            </div>

            <hr class="mt-4 mb-5">

            <Pricing></Pricing>

            <hr class="mt-4 mb-5">

            <div class="row">
                <div class="col-lg-2 col-12 mb-3 mb-lg-0">
                    <div class="settings-group-header">
                        <h2>Australian government incentives</h2>
                    </div>
                </div>
                <div class="col-lg-5 col-12">

                    <div class="settings-group-item">
                        <label class="form-label-title" for="">STC price</label>
                        <input class="form-control" name="" id="">
                    </div>

                    <div class="settings-group-item">
                        <label class="form-label-title" for="">LGC price</label>
                        <input class="form-control" name="" id="">
                    </div>

                    <div class="settings-group-item">
                        <label  class="form-label-title d-flex justify-content-start align-items-center">
                            <input  class="form-check-input" type="checkbox" id="checkboxNoLabel" aria-label="..." value="" autocompleted="">
                            <span  class="fw-bold ms-3">Automatically add state-based rebates</span>
                        </label>
                        <span class="form-input-commant">If enabled, new designs will be created with rebates applicable to their location. Rebates for specific projects can be edited after they are added.</span>
                    </div>

                    <div class="settings-group-item">
                        <label class="form-label-title" for="">Installation year</label>
                        <input class="form-control" name="" id="">
                        <span class="form-input-commant">If left blank, the current year will be used as the installation year. The installation year is used to calculate the remaining deeming period of STCs.</span>
                    </div>
                    <div class="">
                        <button class="btn btn-primary fw-bold">Save Settings</button>
                    </div>
                </div>
            </div>

            <hr class="mt-4 mb-5">

            <div class="row">
                <div class="col-lg-2 col-12 mb-3 mb-lg-0">
                    <div class="settings-group-header">
                        <h2>Other settings</h2>
                    </div>
                </div>
                <div class="col-lg-5 col-12">

                    <div class="settings-group-item">
                        <label class="form-label-title" for="">Notes template</label>
                        <textarea class="form-control" rows="5"></textarea>
                    </div>
                    
                    <div class="">
                        <button class="btn btn-primary fw-bold">Save Settings</button>
                    </div>
                </div>
            </div>

            <br><br><br><br><br><br>
        </section>
    </div>

  </div>

</template>

<style lang="scss">
</style>