<script>
import vueCustomScrollbar from 'vue-custom-scrollbar/src/vue-scrollbar.vue'
import "vue-custom-scrollbar/dist/vueScrollbar.css";
import Pricing from './components/Pricing.vue';

export default {
  name:'ProfileIndex',
    data() {
      return{
      }
    },
    components:{
    vueCustomScrollbar,
    Pricing
}
  }
  
</script>

<template>

  <vue-custom-scrollbar :settings="{ suppressScrollY: false, suppressScrollX: false, wheelPropagation: false, wheelSpeed:0.5 }" class="content">
    
    <div class="content-header">
        <h1 class="mb-3">Solar design</h1>
        <p class="w-75 sub-title pe-5">
            The settings below are used as default values for your Observer solar designs. All new designs will be created with these values.
            <br><br>
            Changes to these settings <strong>will not affect</strong> your existing designs.
        </p>
    </div>

    <div class="content-body">
        <section class="">
            
            <div class="row">
                <div class="col-lg-3 col-3">
                    <div class="settings-group-header">
                        <h2>Solar system</h2>
                        <span class="sub-title">The default layout and configuration of the solar system.</span>
                    </div>
                </div>
                <div class="col-lg-5 col-9">

                    <div class="settings-group-item">
                        <label class="form-label-title" for="">Panel tilt angle</label>
                        <input type="text" class="form-control form-control-sm form-control-input form-control-lg">
                        <span class="form-input-commant">All new panels placed in the editor will be tilted to this angle. Panels can be tilted to any angle after placing them.</span>
                    </div>
                    <div class="settings-group-item">
                        <label class="form-label-title" for="">System efficiency</label>
                        <input type="text" class="form-control form-control-sm form-control-input form-control-lg">
                    </div>
                    <div class="settings-group-item">
                        <label class="form-label-title" for="">Self-consumption</label>
                        <input type="text" class="form-control form-control-sm form-control-input form-control-lg">
                        <span class="form-input-commant">The portion of electricity generated by the solar system that is consumed by the customer.</span>
                    </div>
                    <div class="settings-group-item">
                        <label class="form-label-title" for="">Export limit (instantaneous)</label>
                        <input type="text" class="form-control form-control-sm form-control-input form-control-lg">
                    </div>
                    <div class="settings-group-item">
                        <label class="form-label-title" for="">Installation days</label>
                        <input type="text" class="form-control form-control-sm form-control-input form-control-lg">
                        <span class="form-input-commant">When you create a design, it will be marked for installation this many days in the future.</span>
                    </div>
                    <div class="">
                        <button class="btn btn-primary fw-bold">Save Settings</button>
                    </div>
                </div>
            </div>

            <hr class="mt-4 mb-5">

            <div class="row">
                <div class="col-lg-3 col-3">
                    <div class="settings-group-header">
                        <h2>Editor</h2>
                        <span class="sub-title">These settings customise the map editor.</span>
                    </div>
                </div>
                <div class="col-lg-5 col-9">

                    <div class="settings-group-item">
                        <label class="form-label-title" for="">Azimuth basis</label>
                        <div class="select-box">
                            <select class="form-control form-control-sm form-control-input form-control-lg" name="" id="">
                                <option value="">North</option>
                            </select>
                        </div>
                        <span class="form-input-commant">Azimuth will be shown as 0 when panels are pointed at this pole.</span>
                    </div>
                    <div class="">
                        <button class="btn btn-primary fw-bold">Save Settings</button>
                    </div>
                </div>
            </div>

            <hr class="mt-4 mb-5">

            <div class="row">
                <div class="col-lg-3 col-3">
                    <div class="settings-group-header">
                        <h2>Financial settings</h2>
                        <span class="sub-title">These settings affect the solar system's financial outcomes.</span>
                    </div>
                </div>
                <div class="col-lg-5 col-9">

                    <div class="settings-group-item">
                        <label class="form-label-title" for="">Financial term (years)</label>
                        <input class="form-control form-control-sm form-control-input form-control-lg" name="" id="">
                        <span class="form-input-commant">The period of time assigned as the lifespan of the purchased system or investment. This is typically between 20 to 30 years as per manufacturers warranty.</span>
                    </div>
                    <div class="">
                        <button class="btn btn-primary fw-bold">Save Settings</button>
                    </div>
                </div>
            </div>

            <hr class="mt-4 mb-5">

            <div class="row">
                <div class="col-lg-3 col-3">
                    <div class="settings-group-header">
                        <h2>Electricity tariffs</h2>
                    </div>
                </div>
                <div class="col-lg-5 col-9">

                    <div class="settings-group-item">
                        <label class="form-label-title" for="">Quarterly bill</label>
                        <input class="form-control form-control-sm form-control-input form-control-lg" name="" id="">
                    </div>

                    <div class="settings-group-item">
                        <label class="form-label-title" for="">Electricity rate (per kWh)</label>
                        <input class="form-control form-control-sm form-control-input form-control-lg" name="" id="">
                    </div>

                    <div class="settings-group-item">
                        <label class="form-label-title" for="">Feed in tariff (per kWh)</label>
                        <input class="form-control form-control-sm form-control-input form-control-lg" name="" id="">
                    </div>

                    <div class="settings-group-item">
                        <label class="form-label-title" for="">Daily supply charge</label>
                        <input class="form-control form-control-sm form-control-input form-control-lg" name="" id="">
                    </div>
                    <div class="">
                        <button class="btn btn-primary fw-bold">Save Settings</button>
                    </div>
                </div>
            </div>

            <hr class="mt-4 mb-5">

            <Pricing></Pricing>

            <hr class="mt-4 mb-5">

            <div class="row">
                <div class="col-lg-3 col-3">
                    <div class="settings-group-header">
                        <h2>Australian government incentives</h2>
                    </div>
                </div>
                <div class="col-lg-5 col-9">

                    <div class="settings-group-item">
                        <label class="form-label-title" for="">STC price</label>
                        <input class="form-control form-control-sm form-control-input form-control-lg" name="" id="">
                    </div>

                    <div class="settings-group-item">
                        <label class="form-label-title" for="">LGC price</label>
                        <input class="form-control form-control-sm form-control-input form-control-lg" name="" id="">
                    </div>

                    <div class="settings-group-item">
                        <label  class="form-label-title d-flex justify-content-start align-items-center">
                            <input  class="form-check-input" type="checkbox" id="checkboxNoLabel" aria-label="..." value="" autocompleted="">
                            <span  class="fw-bold ms-3">Automatically add state-based rebates</span>
                        </label>
                        <span class="form-input-commant">If enabled, new designs will be created with rebates applicable to their location. Rebates for specific projects can be edited after they are added.</span>
                    </div>

                    <div class="settings-group-item">
                        <label class="form-label-title" for="">Installation year</label>
                        <input class="form-control form-control-sm form-control-input form-control-lg" name="" id="">
                        <span class="form-input-commant">If left blank, the current year will be used as the installation year. The installation year is used to calculate the remaining deeming period of STCs.</span>
                    </div>
                    <div class="">
                        <button class="btn btn-primary fw-bold">Save Settings</button>
                    </div>
                </div>
            </div>

            <hr class="mt-4 mb-5">

            <div class="row">
                <div class="col-lg-3 col-3">
                    <div class="settings-group-header">
                        <h2>Other settings</h2>
                    </div>
                </div>
                <div class="col-lg-8 col-9">

                    <div class="settings-group-item">
                        <label class="form-label-title" for="">Notes template</label>
                        <textarea class="form-control form-control-sm form-control-input form-control-lg" rows="5"></textarea>
                    </div>
                    
                    <div class="">
                        <button class="btn btn-primary fw-bold">Save Settings</button>
                    </div>
                </div>
            </div>

            <br><br><br><br><br><br>
        </section>
    </div>

  </vue-custom-scrollbar>

</template>

<style lang="scss">
.pricing-list-group{
    box-shadow: rgba(0, 0, 0, 0.1) 0px 1px 3px 0px, rgba(0, 0, 0, 0.06) 0px 1px 2px 0px;
    .list-group-item{
        &:first-child{
            border-top-left-radius:5px;
            border-top-right-radius:5px;
        }
        &:last-child{
            border-bottom-left-radius:5px;
            border-bottom-right-radius:5px;
        }
    }
}
.proposal-pages{
    .proposal-pages__item{
        margin: 1rem 1rem 1rem 0;
        .page__name{
            box-sizing: border-box;
            color: #9aa5b1;
            font-size: 12px;
            font-weight: 700;
            margin-bottom: 0.5rem;
            line-height: 15px;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
            max-width: 105px;
            text-overflow: ellipsis;
            overflow: hidden;
            white-space: nowrap;
        }
        .page__body{
            position: relative;
            border: 3px solid transparent;
            cursor: pointer;
            transition:all 0.3s;
            border-color:#007ee5; // remove this
            &.active,
            &:hover{
                border-color:#007ee5;
                .page__check{
                    fill: #0aa312!important;
                }
            }
            .page__check{
                transition: .3s;
                fill: #0aa312!important; // remove this
                // fill: #99a5b1;
                width: 32px;
                height: 32px;
                position: absolute;
                top: 0.5rem;
                right: 0.5rem;
                background: #fff;
                border-radius: 50%;
            }
        }

    }
}

.proposal-image-uploads__item{
    cursor: pointer;
    position: relative;
    width: 105px;
    height: 148px;
    background-color: #e4e7eb;
    border-radius: 0.25rem;
    border: 1px solid #9aa5b1;
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-pack: center;
    -ms-flex-pack: center;
    justify-content: center;
    line-height: 4.5rem;
    -webkit-box-align: center;
    -ms-flex-align: center;
    align-items: center;
    overflow: hidden;
    margin: 0 1rem 1rem 0;
}



.settings-group-item[data-toggle="list-group-input-toggle"]{
    display: none;
}
.form-check-input{
    .form-check-label{
        font-size: 14px;
    }
    &:checked{
        .form-check-label{
               color:#007ee5;
        }
    }

}

.form-check-input[data-toggle="list-group-input-checked"]:checked ~ .settings-group-item[data-toggle="list-group-input-toggle"]{
        display: block;
}
.list-group {
    .list-group-item{
        &:hover{
            background:#f2f2f2!important;
        }
        .commant{
            font-size: 13px;
            padding: 6px 0px;
            display: block;
            color: #616e7c;
            line-height: 1rem;
            margin-bottom:0px;
        }
    }
}
.btn-check:checked + .btn{
    --mdb-btn-bg: #3b71ca;
    --mdb-btn-color: #fff;
    --mdb-btn-hover-bg: #386bc0;
    --mdb-btn-hover-color: #fff;
    --mdb-btn-focus-bg: #386bc0;
    --mdb-btn-focus-color: #fff;
    --mdb-btn-active-bg: #3566b6;
    --mdb-btn-active-color: #fff;
}
.content-header{
    .sub-title{
        font-size:14px;
    }
}
.content{
    .content-header{
        margin-top: 1.5rem;
        margin-bottom: 3rem;
        padding-left: 1.5rem;
        padding-right: 1.5rem;
        line-height: 1.1;
        h1{
            height: 2rem;
            -webkit-box-align: center;
            -ms-flex-align: center;
            align-items: center;
            font-size: 1.5rem;
            color: #1f2933;
            line-height: 1;
            display: -webkit-box;
            display: -ms-flexbox;
            display: flex;
            font-weight: 600;
        }
    }
    .content-body{
        padding-left: 1.5rem;
        padding-right: 1.5rem;
        .settings-group-header{
            h2{
                font-weight: 600;
                font-size: 1rem;
            }
            .sub-title{
                font-size: 13px;
                padding: 4px 0px;
                display: block;
                color: #616e7c;
                line-height: 1rem;
            }
        }
        .settings-group-item{
            margin-bottom: 25px;
            .form-label-title{
                margin-bottom: 0.25rem;
                line-height: 1.5rem;
                font-weight: 600;
                color: #3e4c59;
                display: -webkit-box;
                display: -ms-flexbox;
                display: flex;
                -webkit-box-align: center;
                -ms-flex-align: center;
                align-items: center;
                -webkit-box-pack: start;
                -ms-flex-pack: start;
                justify-content: flex-start;
                font-size: .875rem;
            }
            .form-control-input{
                background: #f5f7fa;
                border:none;
                border-bottom:2px solid transparent;
                border-radius:0px !important;
                &:focus{
                    box-shadow: none;
                    border-bottom-color: #007ee5;
                }                          
            }
            .select-box{
                position: relative;
                &::before{
                    content: "";
                    position: absolute;
                    top: 47%;
                    right: 15px;
                    border: 4px solid rgb(166 167 170 / 62%);
                    transform: translateY(-50%) rotate(-135deg);
                    border-top-color: transparent;
                    border-left-color: transparent;
                }
                &::after{
                    content: "";
                    position: absolute;
                    top: 53%;
                    right: 15px;
                    border: 4px solid rgb(166 167 170 / 62%);
                    transform: translateY(-50%) rotate(45deg);
                    border-top-color: transparent;
                    border-left-color: transparent;
                }
            } 
            .form-input-commant{
                font-size: 12px;
                padding: 6px 0px;
                display: block;
                color: #616e7c;
                line-height: 1rem;
            }
        }
    }

}

</style>